---
- include_tasks: apt_cache.yml
  when: ansible_pkg_mgr == 'apt' and noobient_apt_cache_updated is not defined

- include_tasks: unixcred.yml

- include_role:
    name: noobient.java
  when: eff_install_java

- include_tasks: package.yml
- include_tasks: service.yml
