---
# https://linuxize.com/post/how-to-install-tomcat-9-on-centos-7/
- name: Deploy Tomcat systemd unit
  template:
    src: tomcat.service.j2
    dest: /etc/systemd/system/tomcat.service
    owner: root
    group: root
    mode: '0644'
  register: tomcat_unit

- name: Reload systemd config # noqa no-handler
  systemd:
    daemon_reload: true
  when: tomcat_unit.changed

# TODO role parameter?
- name: Enable Tomcat service
  systemd:
    name: tomcat.service
    enabled: true

- name: Start Tomcat service
  systemd:
    name: tomcat.service
    state: started
