---
- name: Create Tomcat Unix grop
  group:
    name: tomcat
    gid: "{{ gid | default(tomcat_id) }}"

- name: Create Tomcat Unix user
  user:
    name: tomcat
    uid: "{{ uid | default(tomcat_id) }}"
    group: tomcat
